name: Backend Build & Push

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::487328423713:role/GitHub_Actions_deploy_role"
          aws-region: "us-east-1"

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: backend
          path: backend/Dockerfile
          push: true
          tags: ${{ secrets.ECR_BACKEND_REPO }}:${{ github.run_number }}