name: Frontend Build & Push

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LOGIN_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          path: frontend/Dockerfile
          push: true
          tags: ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.run_number }}
          build-args: |
            REACT_APP_API_BASE_URL=${{ secrets.API_BASE_URL }}